Parameters:
  pInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano
    Description: Enter t2.micro, t2.small, or t2.nano. Default is t2.micro.

  pInstanceAz:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
    Description: Select an availability zone

  pDiskSizeC:
    Type: Number
    Default: 50
    Description: Insert the disk size for C

  pDiskSizeD:
    Type: Number
    Default: 50
    Description: Insert the disk size for D

  pDiskSizeE:
    Type: Number
    Default: 50
    Description: Insert the disk size for E

  pKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Keypair for connection

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref pInstanceAz
      ImageId: ami-0f9a92942448ac56f
      InstanceType: !Ref pInstanceType
      SecurityGroups: [!Ref SSHSecurityGroup]
      KeyName: !Ref pKeyPair
      UserData:
        Fn::Base64:
          !Sub |
          <powershell>
            Stop-Service -Name ShellHWDetection
            Get-Disk | Where PartitionStyle -eq 'raw' | Initialize-Disk -PartitionStyle MBR -PassThru | New-Partition -AssignDriveLetter -UseMaximumSize | Format-Volume -FileSystem NTFS -NewFileSystemLabel "Volume Label" -Confirm:$false
            Start-Service -Name ShellHWDetection
          </powershell>
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref pDiskSizeC
      Volumes:
        - Device: "/dev/sdb"
          VolumeId: !Ref DiskD

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SSH-SecurityGroup
      GroupDescription: Enable port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: 0.0.0.0/0

# Disks can be attached and deattached on fly
  DiskD:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref pDiskSizeD
      AvailabilityZone: !Ref pInstanceAz
    DeletionPolicy: Snapshot

  DiskE:
   Type: AWS::EC2::Volume
   Properties:
     Size: !Ref pDiskSizeE
     AvailabilityZone: !Ref pInstanceAz
   DeletionPolicy: Snapshot

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyInstance
      VolumeId: !Ref DiskE
      Device: /dev/sdc

Outputs:
  PublicIp:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt MyInstance.PublicIp

  InstanceId:
    Description: InstanceId of the EC2 instance
    Value: !Ref MyInstance