Parameters:
  DBInstanceIDParameter:
    Default: mydbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBNameParameter:
    Default: mydb
    Description: My database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBInstanceClassParameter:
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
    Description: DB instance class
    Type: String
  DBAStorageParameter:
    Default: 50
    Description: The size of the database (GB)
    Type: Number
    MinValue: 20
    MaxValue: 200
  DBUsernameParameter:
    Description: Username for database
    Type: String
    MinLength: 1
    MaxLength: 16
  DBPasswordParameter:
    Description: Password for database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
  DBEngineParameter:
    Description: Engine for database
    Type: String
    AllowedValues:
      - mysql
      - mariadb
      - postgres
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIDParameter
      DBName: !Ref DBNameParameter
      DBInstanceClass: !Ref DBInstanceClassParameter
      AllocatedStorage: !Ref DBAStorageParameter
      Engine: !Ref DBEngineParameter
      MasterUsername: !Ref DBUsernameParameter
      MasterUserPassword: !Ref DBPasswordParameter
