Parameters:
  S3NameParameter:
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3NameParameter
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256

