# Mapping enable you to use an input value to determine another value.
---
Mappings:
  RegionMap:  # It will depends of region on console
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e

Resources:
  MyInstance: # Could be any name
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: 
        Fn::FindInMap:
        - RegionMap # Should match with mapping name
        - !Ref AWS::Region
        - AMI  
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0        