Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mySuperBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256

