---
Resources:
  MyInstance: # Resource 1
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: A Simple Value
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:  # Resource 2
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0        