Resources:
  MyInstance: # Could be any name
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-1853ac65 
      InstanceType: t2.micro

Outputs:  # It creates a output tab with information
  AvailabilityZone:
    Value: !GetAtt MyInstance.AvailabilityZone
  PrivateIp:
    Value:
      Fn::GetAtt:
      - MyInstance
      - PrivateIp