---
Resources:
  MyInstance: # Could be any name
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      Tags:
        - Key: Tag1
          Value: !Join [" ", [EC2, Using, Join]]  # Short
        - Key: Tag2
          Value: # Long
            Fn::Join:
            - " "
            - - "EC2"
              - "Using"
              - "Join"  